language: groovy

jdk:
- oraclejdk7
env:
- GRAILS_VERSION=2.4.0

before_install:
- rm -rf ~/.sdkman
- curl -s get.sdkman.io > ~/install_sdk.sh
- chmod 775 ~/install_sdk.sh
- ~/install_sdk.sh
- echo "sdkman_auto_answer=true" > ~/.sdkman/etc/config
- source ~/.sdkman/bin/sdkman-init.sh
- sdk install grails $GRAILS_VERSION || true

branches:
only:
- master

script: grails clean && grails test-app --non-interactive --stacktrace
